[docker]

configs = [
    "selenium/standalone-firefox:4.18.0-20240220", '{"browserName": "firefox"}',
    "selenium/standalone-chrome:4.18.0-20240220", '{"browserName": "chrome"}',
    "selenium/standalone-edge:4.18.0-20240220", '{"browserName": "MicrosoftEdge"}'
]
url = "http://127.0.0.1:2375"

video-image = "selenium/video:ffmpeg-6.1-20240220"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#host = <ip-from-node-machine>
#port = <port-from-node-machine>