apiVersion: v1
kind: Service
metadata:
  name: hub-service
spec:
  selector:
    app: selenium-hub
  ports:
  - port: 4444
    nodePort: 30011
    name: main
  - port: 4442
    nodePort: 30012
    name: se-event-bus-publish-port
  - port: 4443
    nodePort: 30013
    name: se-event-bus-subscribe-port
  type: NodePort